version: '3'

services:
  app:
    image: node:18
    working_dir: /app
    command: npm start
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - app_network

  server:
    image: node:18
    working_dir: /server
    command: npm start
    ports:
      - "80:80"
    volumes:
      - ./server:/server
    networks:
      - server_network

networks:
  app_network:
  server_network:

