services:
   app:
      build: ./app
      restart: unless-stopped
      ports:
         - "3000:3000"
   extension:
      build: ./vscode-extension
      restart: unless-stopped
      ports:
         - "8080:8080"
