services:
   proxy:
      build:
         context: ./proxy
         dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
         - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
         - /etc/ssl/fullchain1.pem:/etc/nginx/fullchain.pem
         - /etc/ssl/privkey1.pem:/etc/nginx/privkey.pem
      ports:
         - "80:80"
         - "443:443"
   api:
      build:
         context: ./server
         dockerfile: Dockerfile
      restart: unless-stopped
      environment:
         - PORT=80
      volumes:
         - ./server/api:/server/api
         - ./server/websocket:/server/websocket
         - ./server/recognitionModels:/server/recognitionModels
         - ./server/server.js:/server/server.js
   app:
      build: ./app
      restart: unless-stopped
      volumes:
         - ./app/src:/app/src
      environment:
         - PORT=80
   db:
      image: mongo:latest
      restart: unless-stopped
      volumes:
         - "./database/data:/data/db"
      env_file:
         - .env
      ports:
         - "2433:27017"
