services:
   proxy:
      build:
         context: ./proxy
         dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
         - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
         - ./proxy/fullchain1.pem:/etc/nginx/templates/fullchain.pem
         - ./proxy/privkey1.pem.template:/etc/nginx/privkey.pem
      ports:
         - "80:80"
         - "443:443"
   api:
      build:
         context: ./server
         dockerfile: Dockerfile
      restart: unless-stopped
      environment:
         - PORT=80
      volumes:
         - ./server/api:/server/api
         - ./server/websocket:/server/websocket
         - ./server/recognitionModels:/server/recognitionModels
         - ./server/server.js:/server/server.js
   app:
      build: ./app
      restart: unless-stopped
      volumes:
         - ./app/src:/app/src
      environment:
         - PORT=80
   db:
      image: mongo:latest
      restart: unless-stopped
      environment:
         # MONGO_INITDB_ROOT_USERNAME:
         # MONGO_INITDB_ROOT_PASSWORD:
         MONGO_INITDB_DATABASE: kuttal
