services:
   proxy:
<<<<<<< HEAD
      build:
         context: ./proxy
         dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
         - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
         - /etc/ssl/fullchain1.pem:/etc/nginx/fullchain.pem
         - /etc/ssl/privkey1.pem:/etc/nginx/privkey.pem
      ports:
         - "80:80"
         - "443:443"
=======
      image: nginx:latest
      restart: unless-stopped
      volumes:
         - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
      ports:
         - "80:80"
<<<<<<< HEAD
>>>>>>> 89988377 (Setup React App and Transcription to Run on VM.)
=======
         - "443:443"
>>>>>>> a18fb3c7 (Changed to handle new VM certificate.)
   api:
      build:
         context: ./server
         dockerfile: Dockerfile
      restart: unless-stopped
      environment:
         - PORT=80
      volumes:
         - ./server/api:/server/api
         - ./server/websocket:/server/websocket
         - ./server/recognitionModels:/server/recognitionModels
         - ./server/server.js:/server/server.js
   app:
      build: ./app
      restart: unless-stopped
      volumes:
         - ./app/src:/app/src
      environment:
         - PORT=80
   db:
      image: mongo:latest
      restart: unless-stopped
<<<<<<< HEAD
      volumes:
         - ./database/data:/data/db
         - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      env_file:
         - .env
      ports:
         - "27017:27017"
=======
      environment:
         # MONGO_INITDB_ROOT_USERNAME:
         # MONGO_INITDB_ROOT_PASSWORD:
         MONGO_INITDB_DATABASE: kuttal
>>>>>>> 89988377 (Setup React App and Transcription to Run on VM.)
