const emotions = {
    Admiration: 1,
    Adoration: 1,
    "Aesthetic Appreciation": 1,
    Amusement: 1,
    Anger: -1,
    Anxiety: -1,
    Awe: 1,
    Awkwardness: 0,
    Boredom: 0,
    Calmness: 1,
    Concentration: 0,
    Confusion: -1,
    Contemplation: 0,
    Contempt: -1,
    Contentment: 1,
    Craving: 0,
    Desire: 1,
    Determination: 1,
    Disappointment: -1,
    Disgust: -1,
    Distress: -1,
    Doubt: -1,
    Ecstasy: 1,
    Embarrassment: -1,
    "Empathic Pain": -1,
    Entrancement: 1,
    Envy: -1,
    Excitement: 1,
    Fear: -1,
    Guilt: -1,
    Horror: -1,
    Interest: 1,
    Joy: 1,
    Love: 1,
    Nostalgia: 0,
    Pain: -1,
    Pride: 1,
    Realization: 0,
    Relief: 1,
    Romance: 1,
    Sadness: -1,
    Satisfaction: 1,
    Shame: -1,
    "Surprise (negative)": -1,
    "Surprise (positive)": 1,
    Sympathy: 1,
    Tiredness: -1,
    Triumph: 1
  };

export default emotions;