services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
      - ./api/static:/app/static
      - ./api/templates:/app/templates
      - ./api/server.js:/app/server.js
  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      # MONGO_INITDB_ROOT_USERNAME:
      # MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: kuttal
